language: php

cache:
  directories:
  - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: SYMFONY_VERSION='~3.4.0'
    - php: 7.3
      env: SYMFONY_VERSION='~4.0'

before_script:
  - phpenv config-add travis.php.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - composer update --prefer-source -o --no-interaction

script: vendor/bin/phpunit -c phpunit.xml.dist
