language: php

cache:
  directories:
  - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.3

before_script:
  - phpenv config-add travis.php.ini
  - composer update --prefer-source -o --no-interaction

script:
    - composer run-script psalm
    - vendor/bin/phpunit -c phpunit.xml.dist
